AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/**/*
    - db/**/*
    - .gemspec/**/*
    - .bundle/**/*
    - vendor/**/*
    - config/**/*
    - script/**/*
    - !ruby/regexp /old_and_unused\.rb$/
    - !ruby/regexp /polishgeeks-[^\/]{2,}\.rb/
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - lib/tasks/**/*.rake
    - lib/tasks/**/*.rb
    - lib/capistrano/**/*.rb
    - lib/capistrano/**/*.cap
AlignParameters:
  Enabled: false
ClassLength:
  CountComments: false
  Max: 200
LineLength:
  Max: 100
MethodLength:
  CountComments: false
  Max: 15
Metrics/AbcSize:
  Max: 25
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Metrics/BlockLength:
  Enabled: false
Naming/FileName:
  Enabled: false

inherit_from:
  - rubocop_rspec.yml
  - rubocop_todo.yml
