RSpec/ExampleLength:
  Max: 10
RSpec/SubjectStub:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
RSpec/MessageChain:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/ReturnFromStub:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/PredicateMatcher:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
